[irc]
    [irc.myirc]
    Server="${IRC_SERVER}"
    Nick="${IRC_NICK}"
    RemoteNickFormat="${IRC_REMOTE_NICK_FORMAT}"
    NickServNick="${IRC_NICKSERV_NICK}"
    NickServPassword="${IRC_NICKSERV_PASSWORD}"
    UseTLS=${IRC_USE_TLS}
    UseSASL=${IRC_USE_SASL}
    SkipTLSVerify=${IRC_SKIP_TLS_VERIFY}
    IgnoreNicks="${IRC_IGNORE_NICKS}"
    
    
[telegram.mytelegram]
#See https://core.telegram.org/bots#6-botfather 
#and https://www.linkedin.com/pulse/telegram-bots-beginners-marco-frau
Token=""
RemoteNickFormat="({PROTOCOL}) &lt;{NICK}&gt; "
MessageFormat="HTMLNick"

[whatsapp.mywhatsapp]
# Number you will use as a relay bot. Tip: Get some disposable sim card, don't rely on 
# your own number.
Number="${WHATSAPP_NUMBER}"

# First time that you login you will need to scan QR code, then credentials will be saved in 
# a session file. 
# If you won't set SessionFile then you will need to scan QR code on every restart.
# optional (by default the session is stored only in memory, till restarting matterbridge)
SessionFile="session-${WHATSAPP_NUMBER}.gob"

# If your terminal is white we need to invert QR code in order for it to be scanned properly
# optional (default false)
QrOnWhiteTerminal=false

# Messages will be seen by other WhatsApp contacts as coming from the bridge. 
# Original nick will be part of the message.
RemoteNickFormat="[{PROTOCOL}] @{NICK}: "
    
[mattermost]
  [mattermost.work]
      Server="${MATTERMOST_SERVER}"
      Team="${MATTERMOST_TEAM}"
      Login="${MATTERMOST_BOT_LOGIN}"
      Password="${MATTERMOST_BOT_PASSWORD}"
      NoTLS=${MATTERMOST_NO_TLS}
      SkipTLSVerify=${MATTERMOST_SKIP_TLS_VERIFY}
      ShowJoinPart=${MATTERMOST_SHOW_JOIN_PART}
      PrefixMessagesWithNick=${MATTERMOST_PREFIX_MSG_WITH_NICK}
      RemoteNickFormat="${MATTERMOST_REMOTE_NICK_FORMAT}"
      NickFormatter="${MATTERMOST_NICK_FORMATTER}"
      NicksPerRow=${MATTERMOST_NICKS_PER_ROW}
      IgnoreNicks="${MATTERMOST_IGNORE_NICKS}"

[[gateway]]
name="mygateway"
enable=true
    [[gateway.inout]]
    account="irc.myirc"
    channel="${IRC_CHANNEL}"

    [[gateway.inout]]
    account="mattermost.work"
    channel="${MATTERMOST_CHANNEL}"

[[gateway]]
name="mygateway2"
enable=true
   [[gateway.inout]]
    account="whatsapp.mywhatsapp"
    channel="${WHATSAPP_CHANNEL}@g.us"

    [[gateway.inout]]
    account="mattermost.work"
    channel="${MATTERMOST_CHANNEL}"

[general]

Plus=true
